### ISSUE TITLE
游戏模式开关OLED标识相反

### ISSUE THREAD

**Issue by LotusOvO** [ChnMasterOG/tp78_v2#1]
https://github.com/ChnMasterOG/tp78_v2/blob/60a05364c2f3d56c20963637949355b431d9ad16/mounriver_project/KEYBOARD_CH582M/HAL/KEYBOARD.c#L403
判断条件貌似写反了

**Comment by ChnMasterOG** [comment]
> https://github.com/ChnMasterOG/tp78_v2/blob/60a05364c2f3d56c20963637949355b431d9ad16/mounriver_project/KEYBOARD_CH582M/HAL/KEYBOARD.c#L403
> 
> 
> 判断条件貌似写反了

马上改掉 :)
