### ISSUE TITLE
单独使用Cap+空格模拟鼠标左右键异常

### ISSUE THREAD

**Issue by LotusOvO** [ChnMasterOG/tp78_v2#3]
键盘与接收器版本: [v2.1.3](https://github.com/ChnMasterOG/tp78_v2/releases/tag/v2.1.3)
1. 单独按下Cap+空格模拟鼠标左右键无反应, 
2. 按下Cap+空格并移动指点杆正常使用

感觉上只有指点杆有移动的情况才有鼠标事件发生, 三种连接模式下都有这个问题.

**Comment by ChnMasterOG** [comment]
确实是BUG，已经改了。
版本 [v2.1.4](https://github.com/ChnMasterOG/tp78_v2/releases/tag/v2.1.4) 修复
